name: sabaidee
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.6.1
  curved_navigation_bar: ^1.0.6
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.0
  flutter_native_splash: ^2.4.1
  font_awesome_flutter: ^10.8.0
  geolocator: ^13.0.2
  glassmorphism: ^3.0.0
  google_sign_in: ^6.2.2
  intl: ^0.20.2
  mailer: ^6.4.1
  permission_handler: ^12.0.0+1
  provider: ^6.1.2
  timezone: ^0.10.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/logos/
    - assets/flags/
    - assets/images/

flutter_native_splash:
  color: "#ffffff" # Background color
  image: assets/logos/logo_no_background_1152x1152.png # Path to your logo image
  android: true
  ios: true
  web: false
