List<Map<String, String>> getCountryListWithTimezones() {
  return [
    {'country': 'Afghanistan', 'timezone': 'UTC+04:30'},
    {'country': 'Albania', 'timezone': 'UTC+01:00'},
    {'country': 'Algeria', 'timezone': 'UTC+01:00'},
    {'country': 'Andorra', 'timezone': 'UTC+01:00'},
    {'country': 'Angola', 'timezone': 'UTC+01:00'},
    {'country': 'Antigua and Barbuda', 'timezone': 'UTC-04:00'},
    {'country': 'Argentina', 'timezone': 'UTC-03:00'},
    {'country': 'Armenia', 'timezone': 'UTC+04:00'},
    {'country': 'Australia', 'timezone': 'UTC+10:00'},
    {'country': 'Austria', 'timezone': 'UTC+01:00'},
    {'country': 'Azerbaijan', 'timezone': 'UTC+04:00'},
    {'country': 'Bahamas', 'timezone': 'UTC-05:00'},
    {'country': 'Bahrain', 'timezone': 'UTC+03:00'},
    {'country': 'Bangladesh', 'timezone': 'UTC+06:00'},
    {'country': 'Barbados', 'timezone': 'UTC-04:00'},
    {'country': 'Belarus', 'timezone': 'UTC+03:00'},
    {'country': 'Belgium', 'timezone': 'UTC+01:00'},
    {'country': 'Belize', 'timezone': 'UTC-06:00'},
    {'country': 'Benin', 'timezone': 'UTC+01:00'},
    {'country': 'Bhutan', 'timezone': 'UTC+06:00'},
    {'country': 'Bolivia', 'timezone': 'UTC-04:00'},
    {'country': 'Bosnia and Herzegovina', 'timezone': 'UTC+01:00'},
    {'country': 'Botswana', 'timezone': 'UTC+02:00'},
    {'country': 'Brazil', 'timezone': 'UTC-03:00'},
    {'country': 'Brunei', 'timezone': 'UTC+08:00'},
    {'country': 'Bulgaria', 'timezone': 'UTC+02:00'},
    {'country': 'Burkina Faso', 'timezone': 'UTC+00:00'},
    {'country': 'Burundi', 'timezone': 'UTC+02:00'},
    {'country': 'Cabo Verde', 'timezone': 'UTC-01:00'},
    {'country': 'Cambodia', 'timezone': 'UTC+07:00'},
    {'country': 'Cameroon', 'timezone': 'UTC+01:00'},
    {'country': 'Canada', 'timezone': 'UTC-05:00'},
    {'country': 'Central African Republic', 'timezone': 'UTC+01:00'},
    {'country': 'Chad', 'timezone': 'UTC+01:00'},
    {'country': 'Chile', 'timezone': 'UTC-03:00'},
    {'country': 'China', 'timezone': 'UTC+08:00'},
    {'country': 'Colombia', 'timezone': 'UTC-05:00'},
    {'country': 'Comoros', 'timezone': 'UTC+03:00'},
    {'country': 'Congo, Democratic Republic of the', 'timezone': 'UTC+01:00'},
    {'country': 'Congo, Republic of the', 'timezone': 'UTC+01:00'},
    {'country': 'Costa Rica', 'timezone': 'UTC-06:00'},
    {'country': 'Croatia', 'timezone': 'UTC+01:00'},
    {'country': 'Cuba', 'timezone': 'UTC-05:00'},
    {'country': 'Cyprus', 'timezone': 'UTC+02:00'},
    {'country': 'Czech Republic', 'timezone': 'UTC+01:00'},
    {'country': 'Denmark', 'timezone': 'UTC+01:00'},
    {'country': 'Djibouti', 'timezone': 'UTC+03:00'},
    {'country': 'Dominica', 'timezone': 'UTC-04:00'},
    {'country': 'Dominican Republic', 'timezone': 'UTC-04:00'},
    {'country': 'Ecuador', 'timezone': 'UTC-05:00'},
    {'country': 'Egypt', 'timezone': 'UTC+02:00'},
    {'country': 'El Salvador', 'timezone': 'UTC-06:00'},
    {'country': 'Equatorial Guinea', 'timezone': 'UTC+01:00'},
    {'country': 'Eritrea', 'timezone': 'UTC+03:00'},
    {'country': 'Estonia', 'timezone': 'UTC+02:00'},
    {'country': 'Eswatini', 'timezone': 'UTC+02:00'},
    {'country': 'Ethiopia', 'timezone': 'UTC+03:00'},
    {'country': 'Fiji', 'timezone': 'UTC+12:00'},
    {'country': 'Finland', 'timezone': 'UTC+02:00'},
    {'country': 'France', 'timezone': 'UTC+01:00'},
    {'country': 'Gabon', 'timezone': 'UTC+01:00'},
    {'country': 'Gambia', 'timezone': 'UTC+00:00'},
    {'country': 'Georgia', 'timezone': 'UTC+04:00'},
    {'country': 'Germany', 'timezone': 'UTC+01:00'},
    {'country': 'Ghana', 'timezone': 'UTC+00:00'},
    {'country': 'Greece', 'timezone': 'UTC+02:00'},
    {'country': 'Grenada', 'timezone': 'UTC-04:00'},
    {'country': 'Guatemala', 'timezone': 'UTC-06:00'},
    {'country': 'Guinea', 'timezone': 'UTC+00:00'},
    {'country': 'Guinea-Bissau', 'timezone': 'UTC+00:00'},
    {'country': 'Guyana', 'timezone': 'UTC-04:00'},
    {'country': 'Haiti', 'timezone': 'UTC-05:00'},
    {'country': 'Honduras', 'timezone': 'UTC-06:00'},
    {'country': 'Hungary', 'timezone': 'UTC+01:00'},
    {'country': 'Iceland', 'timezone': 'UTC+00:00'},
    {'country': 'India', 'timezone': 'UTC+05:30'},
    {'country': 'Indonesia', 'timezone': 'UTC+07:00'},
    {'country': 'Iran', 'timezone': 'UTC+03:30'},
    {'country': 'Iraq', 'timezone': 'UTC+03:00'},
    {'country': 'Ireland', 'timezone': 'UTC+00:00'},
    {'country': 'Israel', 'timezone': 'UTC+02:00'},
    {'country': 'Italy', 'timezone': 'UTC+01:00'},
    {'country': 'Jamaica', 'timezone': 'UTC-05:00'},
    {'country': 'Japan', 'timezone': 'UTC+09:00'},
    {'country': 'Jordan', 'timezone': 'UTC+02:00'},
    {'country': 'Kazakhstan', 'timezone': 'UTC+06:00'},
    {'country': 'Kenya', 'timezone': 'UTC+03:00'},
    {'country': 'Kiribati', 'timezone': 'UTC+12:00'},
    {'country': 'Korea, North', 'timezone': 'UTC+09:00'},
    {'country': 'Korea, South', 'timezone': 'UTC+09:00'},
    {'country': 'Kosovo', 'timezone': 'UTC+01:00'},
    {'country': 'Kuwait', 'timezone': 'UTC+03:00'},
    {'country': 'Kyrgyzstan', 'timezone': 'UTC+06:00'},
    {'country': 'Laos', 'timezone': 'UTC+07:00'},
    {'country': 'Latvia', 'timezone': 'UTC+02:00'},
    {'country': 'Lebanon', 'timezone': 'UTC+02:00'},
    {'country': 'Lesotho', 'timezone': 'UTC+02:00'},
    {'country': 'Liberia', 'timezone': 'UTC+00:00'},
    {'country': 'Libya', 'timezone': 'UTC+02:00'},
    {'country': 'Liechtenstein', 'timezone': 'UTC+01:00'},
    {'country': 'Lithuania', 'timezone': 'UTC+02:00'},
    {'country': 'Luxembourg', 'timezone': 'UTC+01:00'},
    {'country': 'Madagascar', 'timezone': 'UTC+03:00'},
    {'country': 'Malawi', 'timezone': 'UTC+02:00'},
    {'country': 'Malaysia', 'timezone': 'UTC+08:00'},
    {'country': 'Maldives', 'timezone': 'UTC+05:00'},
    {'country': 'Mali', 'timezone': 'UTC+00:00'},
    {'country': 'Malta', 'timezone': 'UTC+01:00'},
    {'country': 'Marshall Islands', 'timezone': 'UTC+12:00'},
    {'country': 'Mauritania', 'timezone': 'UTC+00:00'},
    {'country': 'Mauritius', 'timezone': 'UTC+04:00'},
    {'country': 'Mexico', 'timezone': 'UTC-06:00'},
    {'country': 'Micronesia', 'timezone': 'UTC+10:00'},
    {'country': 'Moldova', 'timezone': 'UTC+02:00'},
    {'country': 'Monaco', 'timezone': 'UTC+01:00'},
    {'country': 'Mongolia', 'timezone': 'UTC+08:00'},
    {'country': 'Montenegro', 'timezone': 'UTC+01:00'},
    {'country': 'Morocco', 'timezone': 'UTC+01:00'},
    {'country': 'Mozambique', 'timezone': 'UTC+02:00'},
    {'country': 'Myanmar', 'timezone': 'UTC+06:30'},
    {'country': 'Namibia', 'timezone': 'UTC+02:00'},
    {'country': 'Nauru', 'timezone': 'UTC+12:00'},
    {'country': 'Nepal', 'timezone': 'UTC+05:45'},
    {'country': 'Netherlands', 'timezone': 'UTC+01:00'},
    {'country': 'New Zealand', 'timezone': 'UTC+12:00'},
    {'country': 'Nicaragua', 'timezone': 'UTC-06:00'},
    {'country': 'Niger', 'timezone': 'UTC+01:00'},
    {'country': 'Nigeria', 'timezone': 'UTC+01:00'},
    {'country': 'North Macedonia', 'timezone': 'UTC+01:00'},
    {'country': 'Norway', 'timezone': 'UTC+01:00'},
    {'country': 'Oman', 'timezone': 'UTC+04:00'},
    {'country': 'Pakistan', 'timezone': 'UTC+05:00'},
    {'country': 'Palau', 'timezone': 'UTC+09:00'},
    {'country': 'Palestine', 'timezone': 'UTC+02:00'},
    {'country': 'Panama', 'timezone': 'UTC-05:00'},
    {'country': 'Papua New Guinea', 'timezone': 'UTC+10:00'},
    {'country': 'Paraguay', 'timezone': 'UTC-04:00'},
    {'country': 'Peru', 'timezone': 'UTC-05:00'},
    {'country': 'Philippines', 'timezone': 'UTC+08:00'},
    {'country': 'Poland', 'timezone': 'UTC+01:00'},
    {'country': 'Portugal', 'timezone': 'UTC+00:00'},
    {'country': 'Qatar', 'timezone': 'UTC+03:00'},
    {'country': 'Romania', 'timezone': 'UTC+02:00'},
    {'country': 'Russia', 'timezone': 'UTC+03:00'},
    {'country': 'Rwanda', 'timezone': 'UTC+02:00'},
    {'country': 'Saint Kitts and Nevis', 'timezone': 'UTC-04:00'},
    {'country': 'Saint Lucia', 'timezone': 'UTC-04:00'},
    {'country': 'Saint Vincent and the Grenadines', 'timezone': 'UTC-04:00'},
    {'country': 'Samoa', 'timezone': 'UTC+13:00'},
    {'country': 'San Marino', 'timezone': 'UTC+01:00'},
    {'country': 'Sao Tome and Principe', 'timezone': 'UTC+00:00'},
    {'country': 'Saudi Arabia', 'timezone': 'UTC+03:00'},
    {'country': 'Senegal', 'timezone': 'UTC+00:00'},
    {'country': 'Serbia', 'timezone': 'UTC+01:00'},
    {'country': 'Seychelles', 'timezone': 'UTC+04:00'},
    {'country': 'Sierra Leone', 'timezone': 'UTC+00:00'},
    {'country': 'Singapore', 'timezone': 'UTC+08:00'},
    {'country': 'Slovakia', 'timezone': 'UTC+01:00'},
    {'country': 'Slovenia', 'timezone': 'UTC+01:00'},
    {'country': 'Solomon Islands', 'timezone': 'UTC+11:00'},
    {'country': 'Somalia', 'timezone': 'UTC+03:00'},
    {'country': 'South Africa', 'timezone': 'UTC+02:00'},
    {'country': 'South Sudan', 'timezone': 'UTC+03:00'},
    {'country': 'Spain', 'timezone': 'UTC+01:00'},
    {'country': 'Sri Lanka', 'timezone': 'UTC+05:30'},
    {'country': 'Sudan', 'timezone': 'UTC+02:00'},
    {'country': 'Suriname', 'timezone': 'UTC-03:00'},
    {'country': 'Sweden', 'timezone': 'UTC+01:00'},
    {'country': 'Switzerland', 'timezone': 'UTC+01:00'},
    {'country': 'Syria', 'timezone': 'UTC+02:00'},
    {'country': 'Taiwan', 'timezone': 'UTC+08:00'},
    {'country': 'Tajikistan', 'timezone': 'UTC+05:00'},
    {'country': 'Tanzania', 'timezone': 'UTC+03:00'},
    {'country': 'Thailand', 'timezone': 'UTC+07:00'},
    {'country': 'Timor-Leste', 'timezone': 'UTC+09:00'},
    {'country': 'Togo', 'timezone': 'UTC+00:00'},
    {'country': 'Tonga', 'timezone': 'UTC+13:00'},
    {'country': 'Trinidad and Tobago', 'timezone': 'UTC-04:00'},
    {'country': 'Tunisia', 'timezone': 'UTC+01:00'},
    {'country': 'Turkey', 'timezone': 'UTC+03:00'},
    {'country': 'Turkmenistan', 'timezone': 'UTC+05:00'},
    {'country': 'Tuvalu', 'timezone': 'UTC+12:00'},
    {'country': 'Uganda', 'timezone': 'UTC+03:00'},
    {'country': 'Ukraine', 'timezone': 'UTC+02:00'},
    {'country': 'United Arab Emirates', 'timezone': 'UTC+04:00'},
    {'country': 'United Kingdom', 'timezone': 'UTC+00:00'},
    {'country': 'United States', 'timezone': 'UTC-05:00'},
    {'country': 'Uruguay', 'timezone': 'UTC-03:00'},
    {'country': 'Uzbekistan', 'timezone': 'UTC+05:00'},
    {'country': 'Vanuatu', 'timezone': 'UTC+11:00'},
    {'country': 'Vatican City', 'timezone': 'UTC+01:00'},
    {'country': 'Venezuela', 'timezone': 'UTC-04:00'},
    {'country': 'Vietnam', 'timezone': 'UTC+07:00'},
    {'country': 'Yemen', 'timezone': 'UTC+03:00'},
    {'country': 'Zambia', 'timezone': 'UTC+02:00'},
    {'country': 'Zimbabwe', 'timezone': 'UTC+02:00'},
  ];
}

List<String> getCountryNames() {
  return getCountryListWithTimezones().map((country) => country['country']!).toList();
}