List<Map<String, String>> getCountryList2() {
  return [
   {'country': 'Test Country', 'timezone': 'UTC+00:00', 'filename': 'af.png'},
   {'country': 'Afghanistan', 'timezone': 'UTC+04:30', 'filename': 'af.png'},
    {'country': 'Albania', 'timezone': 'UTC+01:00', 'filename': 'al.png'},
    {'country': 'Algeria', 'timezone': 'UTC+01:00', 'filename': 'dz.png'},
    {'country': 'Andorra', 'timezone': 'UTC+01:00', 'filename': 'ad.png'},
    {'country': 'Angola', 'timezone': 'UTC+01:00', 'filename': 'ao.png'},
    {'country': 'Antigua and Barbuda', 'timezone': 'UTC-04:00', 'filename': 'ag.png'},
    {'country': 'Argentina', 'timezone': 'UTC-03:00', 'filename': 'ar.png'},
    {'country': 'Armenia', 'timezone': 'UTC+04:00', 'filename': 'am.png'},
    {'country': 'Australia', 'timezone': 'UTC+10:00', 'filename': 'au.png'},
    {'country': 'Austria', 'timezone': 'UTC+01:00', 'filename': 'at.png'},
    {'country': 'Azerbaijan', 'timezone': 'UTC+04:00', 'filename': 'az.png'},
    {'country': 'Bahamas', 'timezone': 'UTC-05:00', 'filename': 'bs.png'},
    {'country': 'Bahrain', 'timezone': 'UTC+03:00', 'filename': 'bh.png'},
    {'country': 'Bangladesh', 'timezone': 'UTC+06:00', 'filename': 'bd.png'},
    {'country': 'Barbados', 'timezone': 'UTC-04:00', 'filename': 'bb.png'},
    {'country': 'Belarus', 'timezone': 'UTC+03:00', 'filename': 'by.png'},
    {'country': 'Belgium', 'timezone': 'UTC+01:00', 'filename': 'be.png'},
    {'country': 'Belize', 'timezone': 'UTC-06:00', 'filename': 'bz.png'},
    {'country': 'Benin', 'timezone': 'UTC+01:00', 'filename': 'bj.png'},
    {'country': 'Bhutan', 'timezone': 'UTC+06:00', 'filename': 'bt.png'},
    {'country': 'Bolivia', 'timezone': 'UTC-04:00', 'filename': 'bo.png'},
    {'country': 'Bosnia and Herzegovina', 'timezone': 'UTC+01:00', 'filename': 'ba.png'},
    {'country': 'Botswana', 'timezone': 'UTC+02:00', 'filename': 'bw.png'},
    {'country': 'Brazil', 'timezone': 'UTC-03:00', 'filename': 'br.png'},
    {'country': 'Brunei', 'timezone': 'UTC+08:00', 'filename': 'bn.png'},
    {'country': 'Bulgaria', 'timezone': 'UTC+02:00', 'filename': 'bg.png'},
    {'country': 'Burkina Faso', 'timezone': 'UTC+00:00', 'filename': 'bf.png'},
    {'country': 'Burundi', 'timezone': 'UTC+02:00', 'filename': 'bi.png'},
    {'country': 'Cabo Verde', 'timezone': 'UTC-01:00', 'filename': 'cv.png'},
    {'country': 'Cambodia', 'timezone': 'UTC+07:00', 'filename': 'kh.png'},
    {'country': 'Cameroon', 'timezone': 'UTC+01:00', 'filename': 'cm.png'},
    {'country': 'Canada', 'timezone': 'UTC-05:00', 'filename': 'ca.png'},
    {'country': 'Central African Republic', 'timezone': 'UTC+01:00', 'filename': 'cf.png'},
    {'country': 'Chad', 'timezone': 'UTC+01:00', 'filename': 'td.png'},
    {'country': 'Chile', 'timezone': 'UTC-03:00', 'filename': 'cl.png'},
    {'country': 'China', 'timezone': 'UTC+08:00', 'filename': 'cn.png'},
    {'country': 'Colombia', 'timezone': 'UTC-05:00', 'filename': 'co.png'},
    {'country': 'Comoros', 'timezone': 'UTC+03:00', 'filename': 'km.png'},
    {'country': 'Congo, Democratic Republic', 'timezone': 'UTC+01:00', 'filename': 'cd.png'},
    {'country': 'Congo, Republic of the', 'timezone': 'UTC+01:00', 'filename': 'cg.png'},
    {'country': 'Costa Rica', 'timezone': 'UTC-06:00', 'filename': 'cr.png'},
    {'country': 'Croatia', 'timezone': 'UTC+01:00', 'filename': 'hr.png'},
    {'country': 'Cuba', 'timezone': 'UTC-05:00', 'filename': 'cu.png'},
    {'country': 'Cyprus', 'timezone': 'UTC+02:00', 'filename': 'cy.png'},
    {'country': 'Czech Republic', 'timezone': 'UTC+01:00', 'filename': 'cz.png'},
    {'country': 'Denmark', 'timezone': 'UTC+01:00', 'filename': 'dk.png'},
    {'country': 'Djibouti', 'timezone': 'UTC+03:00', 'filename': 'dj.png'},
    {'country': 'Dominica', 'timezone': 'UTC-04:00', 'filename': 'dm.png'},
    {'country': 'Dominican Republic', 'timezone': 'UTC-04:00', 'filename': 'do.png'},
    {'country': 'Ecuador', 'timezone': 'UTC-05:00', 'filename': 'ec.png'},
    {'country': 'Egypt', 'timezone': 'UTC+02:00', 'filename': 'eg.png'},
    {'country': 'El Salvador', 'timezone': 'UTC-06:00', 'filename': 'sv.png'},
    {'country': 'Equatorial Guinea', 'timezone': 'UTC+01:00', 'filename': 'gq.png'},
    {'country': 'Eritrea', 'timezone': 'UTC+03:00', 'filename': 'er.png'},
    {'country': 'Estonia', 'timezone': 'UTC+02:00', 'filename': 'ee.png'},
    {'country': 'Eswatini', 'timezone': 'UTC+02:00', 'filename': 'sz.png'},
    {'country': 'Ethiopia', 'timezone': 'UTC+03:00', 'filename': 'et.png'},
    {'country': 'Fiji', 'timezone': 'UTC+12:00', 'filename': 'fj.png'},
    {'country': 'Finland', 'timezone': 'UTC+02:00', 'filename': 'fi.png'},
    {'country': 'France', 'timezone': 'UTC+01:00', 'filename': 'fr.png'},
    {'country': 'Gabon', 'timezone': 'UTC+01:00', 'filename': 'ga.png'},
    {'country': 'Gambia', 'timezone': 'UTC+00:00', 'filename': 'gm.png'},
    {'country': 'Georgia', 'timezone': 'UTC+04:00', 'filename': 'ge.png'},
    {'country': 'Germany', 'timezone': 'UTC+01:00', 'filename': 'de.png'},
    {'country': 'Ghana', 'timezone': 'UTC+00:00', 'filename': 'gh.png'},
    {'country': 'Greece', 'timezone': 'UTC+02:00', 'filename': 'gr.png'},
    {'country': 'Grenada', 'timezone': 'UTC-04:00', 'filename': 'gd.png'},
    {'country': 'Guatemala', 'timezone': 'UTC-06:00', 'filename': 'gt.png'},
    {'country': 'Guinea', 'timezone': 'UTC+00:00', 'filename': 'gn.png'},
    {'country': 'Guinea-Bissau', 'timezone': 'UTC+00:00', 'filename': 'gw.png'},
    {'country': 'Guyana', 'timezone': 'UTC-04:00', 'filename': 'gy.png'},
    {'country': 'Haiti', 'timezone': 'UTC-05:00', 'filename': 'ht.png'},
    {'country': 'Honduras', 'timezone': 'UTC-06:00', 'filename': 'hn.png'},
    {'country': 'Hungary', 'timezone': 'UTC+01:00', 'filename': 'hu.png'},
    {'country': 'Iceland', 'timezone': 'UTC+00:00', 'filename': 'is.png'},
    {'country': 'India', 'timezone': 'UTC+05:30', 'filename': 'in.png'},
    {'country': 'Indonesia', 'timezone': 'UTC+07:00', 'filename': 'id.png'},
    {'country': 'Iran', 'timezone': 'UTC+03:30', 'filename': 'ir.png'},
    {'country': 'Iraq', 'timezone': 'UTC+03:00', 'filename': 'iq.png'},
    {'country': 'Ireland', 'timezone': 'UTC+00:00', 'filename': 'ie.png'},
    {'country': 'Israel', 'timezone': 'UTC+02:00', 'filename': 'il.png'},
    {'country': 'Italy', 'timezone': 'UTC+01:00', 'filename': 'it.png'},
    {'country': 'Jamaica', 'timezone': 'UTC-05:00', 'filename': 'jm.png'},
    {'country': 'Japan', 'timezone': 'UTC+09:00', 'filename': 'jp.png'},
    {'country': 'Jordan', 'timezone': 'UTC+02:00', 'filename': 'jo.png'},
    {'country': 'Kazakhstan', 'timezone': 'UTC+06:00', 'filename': 'kz.png'},
    {'country': 'Kenya', 'timezone': 'UTC+03:00', 'filename': 'ke.png'},
    {'country': 'Kiribati', 'timezone': 'UTC+12:00', 'filename': 'ki.png'},
    {'country': 'Korea, North', 'timezone': 'UTC+09:00', 'filename': 'kp.png'},
    {'country': 'Korea, South', 'timezone': 'UTC+09:00', 'filename': 'kr.png'},
    {'country': 'Kosovo', 'timezone': 'UTC+01:00', 'filename': 'xk.png'},
    {'country': 'Kuwait', 'timezone': 'UTC+03:00', 'filename': 'kw.png'},
    {'country': 'Kyrgyzstan', 'timezone': 'UTC+06:00', 'filename': 'kg.png'},
    {'country': 'Laos', 'timezone': 'UTC+07:00', 'filename': 'la.png'},
    {'country': 'Latvia', 'timezone': 'UTC+02:00', 'filename': 'lv.png'},
    {'country': 'Lebanon', 'timezone': 'UTC+02:00', 'filename': 'lb.png'},
    {'country': 'Lesotho', 'timezone': 'UTC+02:00', 'filename': 'ls.png'},
    {'country': 'Liberia', 'timezone': 'UTC+00:00', 'filename': 'lr.png'},
    {'country': 'Libya', 'timezone': 'UTC+02:00', 'filename': 'ly.png'},
    {'country': 'Liechtenstein', 'timezone': 'UTC+01:00', 'filename': 'li.png'},
    {'country': 'Lithuania', 'timezone': 'UTC+02:00', 'filename': 'lt.png'},
    {'country': 'Luxembourg', 'timezone': 'UTC+01:00', 'filename': 'lu.png'},
    {'country': 'Madagascar', 'timezone': 'UTC+03:00', 'filename': 'mg.png'},
    {'country': 'Malawi', 'timezone': 'UTC+02:00', 'filename': 'mw.png'},
    {'country': 'Malaysia', 'timezone': 'UTC+08:00', 'filename': 'my.png'},
    {'country': 'Maldives', 'timezone': 'UTC+05:00', 'filename': 'mv.png'},
    {'country': 'Mali', 'timezone': 'UTC+00:00', 'filename': 'ml.png'},
    {'country': 'Malta', 'timezone': 'UTC+01:00', 'filename': 'mt.png'},
    {'country': 'Marshall Islands', 'timezone': 'UTC+12:00', 'filename': 'mh.png'},
    {'country': 'Mauritania', 'timezone': 'UTC+00:00', 'filename': 'mr.png'},
    {'country': 'Mauritius', 'timezone': 'UTC+04:00', 'filename': 'mu.png'},
    {'country': 'Mexico', 'timezone': 'UTC-06:00', 'filename': 'mx.png'},
    {'country': 'Micronesia', 'timezone': 'UTC+10:00', 'filename': 'fm.png'},
    {'country': 'Moldova', 'timezone': 'UTC+02:00', 'filename': 'md.png'},
    {'country': 'Monaco', 'timezone': 'UTC+01:00', 'filename': 'mc.png'},
    {'country': 'Mongolia', 'timezone': 'UTC+08:00', 'filename': 'mn.png'},
    {'country': 'Montenegro', 'timezone': 'UTC+01:00', 'filename': 'me.png'},
    {'country': 'Morocco', 'timezone': 'UTC+01:00', 'filename': 'ma.png'},
    {'country': 'Mozambique', 'timezone': 'UTC+02:00', 'filename': 'mz.png'},
    {'country': 'Myanmar', 'timezone': 'UTC+06:30', 'filename': 'mm.png'},
    {'country': 'Namibia', 'timezone': 'UTC+02:00', 'filename': 'na.png'},
    {'country': 'Nauru', 'timezone': 'UTC+12:00', 'filename': 'nr.png'},
    {'country': 'Nepal', 'timezone': 'UTC+05:45', 'filename': 'np.png'},
    {'country': 'Netherlands', 'timezone': 'UTC+01:00', 'filename': 'nl.png'},
    {'country': 'New Zealand', 'timezone': 'UTC+12:00', 'filename': 'nz.png'},
    {'country': 'Nicaragua', 'timezone': 'UTC-06:00', 'filename': 'ni.png'},
    {'country': 'Niger', 'timezone': 'UTC+01:00', 'filename': 'ne.png'},
    {'country': 'Nigeria', 'timezone': 'UTC+01:00', 'filename': 'ng.png'},
    {'country': 'North Macedonia', 'timezone': 'UTC+01:00', 'filename': 'mk.png'},
    {'country': 'Norway', 'timezone': 'UTC+01:00', 'filename': 'no.png'},
    {'country': 'Oman', 'timezone': 'UTC+04:00', 'filename': 'om.png'},
    {'country': 'Pakistan', 'timezone': 'UTC+05:00', 'filename': 'pk.png'},
    {'country': 'Palau', 'timezone': 'UTC+09:00', 'filename': 'pw.png'},
    {'country': 'Palestine', 'timezone': 'UTC+02:00', 'filename': 'ps.png'},
    {'country': 'Panama', 'timezone': 'UTC-05:00', 'filename': 'pa.png'},
    {'country': 'Papua New Guinea', 'timezone': 'UTC+10:00', 'filename': 'pg.png'},
    {'country': 'Paraguay', 'timezone': 'UTC-04:00', 'filename': 'py.png'},
    {'country': 'Peru', 'timezone': 'UTC-05:00', 'filename': 'pe.png'},
    {'country': 'Philippines', 'timezone': 'UTC+08:00', 'filename': 'ph.png'},
    {'country': 'Poland', 'timezone': 'UTC+01:00', 'filename': 'pl.png'},
    {'country': 'Portugal', 'timezone': 'UTC+00:00', 'filename': 'pt.png'},
    {'country': 'Qatar', 'timezone': 'UTC+03:00', 'filename': 'qa.png'},
    {'country': 'Romania', 'timezone': 'UTC+02:00', 'filename': 'ro.png'},
    {'country': 'Russia', 'timezone': 'UTC+03:00', 'filename': 'ru.png'},
    {'country': 'Rwanda', 'timezone': 'UTC+02:00', 'filename': 'rw.png'},
    {'country': 'Saint Kitts and Nevis', 'timezone': 'UTC-04:00', 'filename': 'kn.png'},
    {'country': 'Saint Lucia', 'timezone': 'UTC-04:00', 'filename': 'lc.png'},
    {'country': 'Saint Vincent and the Grenadines', 'timezone': 'UTC-04:00', 'filename': 'vc.png'},
    {'country': 'Samoa', 'timezone': 'UTC+13:00', 'filename': 'ws.png'},
    {'country': 'San Marino', 'timezone': 'UTC+01:00', 'filename': 'sm.png'},
    {'country': 'Sao Tome and Principe', 'timezone': 'UTC+00:00', 'filename': 'st.png'},
    {'country': 'Saudi Arabia', 'timezone': 'UTC+03:00', 'filename': 'sa.png'},
    {'country': 'Senegal', 'timezone': 'UTC+00:00', 'filename': 'sn.png'},
    {'country': 'Serbia', 'timezone': 'UTC+01:00', 'filename': 'rs.png'},
    {'country': 'Seychelles', 'timezone': 'UTC+04:00', 'filename': 'sc.png'},
    {'country': 'Sierra Leone', 'timezone': 'UTC+00:00', 'filename': 'sl.png'},
    {'country': 'Singapore', 'timezone': 'UTC+08:00', 'filename': 'sg.png'},
    {'country': 'Slovakia', 'timezone': 'UTC+01:00', 'filename': 'sk.png'},
    {'country': 'Slovenia', 'timezone': 'UTC+01:00', 'filename': 'si.png'},
      {'country': 'Solomon Islands', 'timezone': 'UTC+11:00', 'filename': 'sb.png'},
    {'country': 'Somalia', 'timezone': 'UTC+03:00', 'filename': 'so.png'},
    {'country': 'South Africa', 'timezone': 'UTC+02:00', 'filename': 'za.png'},
    {'country': 'South Sudan', 'timezone': 'UTC+03:00', 'filename': 'ss.png'},
    {'country': 'Spain', 'timezone': 'UTC+01:00', 'filename': 'es.png'},
    {'country': 'Sri Lanka', 'timezone': 'UTC+05:30', 'filename': 'lk.png'},
    {'country': 'Sudan', 'timezone': 'UTC+02:00', 'filename': 'sd.png'},
    {'country': 'Suriname', 'timezone': 'UTC-03:00', 'filename': 'sr.png'},
    {'country': 'Sweden', 'timezone': 'UTC+01:00', 'filename': 'se.png'},
    {'country': 'Switzerland', 'timezone': 'UTC+01:00', 'filename': 'ch.png'},
    {'country': 'Syria', 'timezone': 'UTC+02:00', 'filename': 'sy.png'},
    {'country': 'Taiwan', 'timezone': 'UTC+08:00', 'filename': 'tw.png'},
    {'country': 'Tajikistan', 'timezone': 'UTC+05:00', 'filename': 'tj.png'},
    {'country': 'Tanzania', 'timezone': 'UTC+03:00', 'filename': 'tz.png'},
    {'country': 'Thailand', 'timezone': 'UTC+07:00', 'filename': 'th.png'},
    {'country': 'Timor-Leste', 'timezone': 'UTC+09:00', 'filename': 'tl.png'},
    {'country': 'Togo', 'timezone': 'UTC+00:00', 'filename': 'tg.png'},
    {'country': 'Tonga', 'timezone': 'UTC+13:00', 'filename': 'to.png'},
    {'country': 'Trinidad and Tobago', 'timezone': 'UTC-04:00', 'filename': 'tt.png'},
    {'country': 'Tunisia', 'timezone': 'UTC+01:00', 'filename': 'tn.png'},
    {'country': 'Turkey', 'timezone': 'UTC+03:00', 'filename': 'tr.png'},
    {'country': 'Turkmenistan', 'timezone': 'UTC+05:00', 'filename': 'tm.png'},
    {'country': 'Tuvalu', 'timezone': 'UTC+12:00', 'filename': 'tv.png'},
    {'country': 'Uganda', 'timezone': 'UTC+03:00', 'filename': 'ug.png'},
    {'country': 'Ukraine', 'timezone': 'UTC+02:00', 'filename': 'ua.png'},
    {'country': 'United Arab Emirates', 'timezone': 'UTC+04:00', 'filename': 'ae.png'},
    {'country': 'United Kingdom', 'timezone': 'UTC+00:00', 'filename': 'gb.png'},
    {'country': 'United States', 'timezone': 'UTC-05:00', 'filename': 'us.png'},
    {'country': 'Uruguay', 'timezone': 'UTC-03:00', 'filename': 'uy.png'},
    {'country': 'Uzbekistan', 'timezone': 'UTC+05:00', 'filename': 'uz.png'},
    {'country': 'Vanuatu', 'timezone': 'UTC+11:00', 'filename': 'vu.png'},
    {'country': 'Venezuela', 'timezone': 'UTC-04:00', 'filename': 've.png'},
    {'country': 'Vietnam', 'timezone': 'UTC+07:00', 'filename': 'vn.png'},
    {'country': 'Yemen', 'timezone': 'UTC+03:00', 'filename': 'ye.png'},
    {'country': 'Zambia', 'timezone': 'UTC+02:00', 'filename': 'zm.png'},
    {'country': 'Zimbabwe', 'timezone': 'UTC+02:00', 'filename': 'zw.png'},
  ];
}