class EmergencyHelpline {
  final String country;
  final String policeNumber;
  final String ambulanceNumber;
  final String fireBrigadeNumber;

  EmergencyHelpline({
    required this.country,
    required this.policeNumber,
    required this.ambulanceNumber,
    required this.fireBrigadeNumber,
  });
}

List<EmergencyHelpline> getEmergencyHelplines() {
  return [
    EmergencyHelpline(country: 'Test Country', policeNumber: '123', ambulanceNumber: '123', fireBrigadeNumber: '123'),
    EmergencyHelpline(country: 'United States', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Canada', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'United Kingdom', policeNumber: '999', ambulanceNumber: '999', fireBrigadeNumber: '999'),
    EmergencyHelpline(country: 'Australia', policeNumber: '000', ambulanceNumber: '000', fireBrigadeNumber: '000'),
    EmergencyHelpline(country: 'New Zealand', policeNumber: '111', ambulanceNumber: '111', fireBrigadeNumber: '111'),
    EmergencyHelpline(country: 'India', policeNumber: '112', ambulanceNumber: '102', fireBrigadeNumber: '101'),
    EmergencyHelpline(country: 'Germany', policeNumber: '110', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'France', policeNumber: '17', ambulanceNumber: '15', fireBrigadeNumber: '18'),
    EmergencyHelpline(country: 'Italy', policeNumber: '112', ambulanceNumber: '118', fireBrigadeNumber: '115'),
    EmergencyHelpline(country: 'Spain', policeNumber: '112', ambulanceNumber: '061', fireBrigadeNumber: '080'),
    EmergencyHelpline(country: 'Japan', policeNumber: '110', ambulanceNumber: '119', fireBrigadeNumber: '119'),
    EmergencyHelpline(country: 'China', policeNumber: '110', ambulanceNumber: '120', fireBrigadeNumber: '119'),
    EmergencyHelpline(country: 'Russia', policeNumber: '102', ambulanceNumber: '103', fireBrigadeNumber: '101'),
    EmergencyHelpline(country: 'Brazil', policeNumber: '190', ambulanceNumber: '192', fireBrigadeNumber: '193'),
    EmergencyHelpline(country: 'Mexico', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'South Africa', policeNumber: '10111', ambulanceNumber: '10177', fireBrigadeNumber: '10177'),
    EmergencyHelpline(country: 'Nigeria', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Egypt', policeNumber: '122', ambulanceNumber: '123', fireBrigadeNumber: '180'),
    EmergencyHelpline(country: 'Saudi Arabia', policeNumber: '999', ambulanceNumber: '997', fireBrigadeNumber: '998'),
    EmergencyHelpline(country: 'United Arab Emirates', policeNumber: '999', ambulanceNumber: '998', fireBrigadeNumber: '997'),
    EmergencyHelpline(country: 'Argentina', policeNumber: '911', ambulanceNumber: '107', fireBrigadeNumber: '100'),
    EmergencyHelpline(country: 'Chile', policeNumber: '133', ambulanceNumber: '131', fireBrigadeNumber: '132'),
    EmergencyHelpline(country: 'Colombia', policeNumber: '123', ambulanceNumber: '123', fireBrigadeNumber: '119'),
    EmergencyHelpline(country: 'Peru', policeNumber: '105', ambulanceNumber: '106', fireBrigadeNumber: '116'),
    EmergencyHelpline(country: 'Venezuela', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'South Korea', policeNumber: '112', ambulanceNumber: '119', fireBrigadeNumber: '119'),
    EmergencyHelpline(country: 'North Korea', policeNumber: '112', ambulanceNumber: '119', fireBrigadeNumber: '119'),
    EmergencyHelpline(country: 'Vietnam', policeNumber: '113', ambulanceNumber: '115', fireBrigadeNumber: '114'),
    EmergencyHelpline(country: 'Thailand', policeNumber: '191', ambulanceNumber: '1669', fireBrigadeNumber: '199'),
    EmergencyHelpline(country: 'Malaysia', policeNumber: '999', ambulanceNumber: '999', fireBrigadeNumber: '994'),
    EmergencyHelpline(country: 'Singapore', policeNumber: '999', ambulanceNumber: '995', fireBrigadeNumber: '995'),
    EmergencyHelpline(country: 'Indonesia', policeNumber: '110', ambulanceNumber: '118', fireBrigadeNumber: '113'),
    EmergencyHelpline(country: 'Philippines', policeNumber: '117', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Pakistan', policeNumber: '15', ambulanceNumber: '115', fireBrigadeNumber: '16'),
    EmergencyHelpline(country: 'Bangladesh', policeNumber: '999', ambulanceNumber: '199', fireBrigadeNumber: '199'),
    EmergencyHelpline(country: 'Sri Lanka', policeNumber: '119', ambulanceNumber: '110', fireBrigadeNumber: '110'),
    EmergencyHelpline(country: 'Nepal', policeNumber: '100', ambulanceNumber: '102', fireBrigadeNumber: '101'),
    EmergencyHelpline(country: 'Bhutan', policeNumber: '113', ambulanceNumber: '112', fireBrigadeNumber: '110'),
    EmergencyHelpline(country: 'Maldives', policeNumber: '119', ambulanceNumber: '102', fireBrigadeNumber: '118'),
    EmergencyHelpline(country: 'Afghanistan', policeNumber: '119', ambulanceNumber: '112', fireBrigadeNumber: '119'),
    EmergencyHelpline(country: 'Iran', policeNumber: '110', ambulanceNumber: '115', fireBrigadeNumber: '125'),
    EmergencyHelpline(country: 'Iraq', policeNumber: '104', ambulanceNumber: '122', fireBrigadeNumber: '115'),
    EmergencyHelpline(country: 'Syria', policeNumber: '112', ambulanceNumber: '110', fireBrigadeNumber: '113'),
    EmergencyHelpline(country: 'Jordan', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Lebanon', policeNumber: '112', ambulanceNumber: '140', fireBrigadeNumber: '175'),
    EmergencyHelpline(country: 'Israel', policeNumber: '100', ambulanceNumber: '101', fireBrigadeNumber: '102'),
    EmergencyHelpline(country: 'Palestine', policeNumber: '100', ambulanceNumber: '101', fireBrigadeNumber: '102'),
    EmergencyHelpline(country: 'Turkey', policeNumber: '155', ambulanceNumber: '112', fireBrigadeNumber: '110'),
    EmergencyHelpline(country: 'Greece', policeNumber: '100', ambulanceNumber: '166', fireBrigadeNumber: '199'),
    EmergencyHelpline(country: 'Cyprus', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Portugal', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Netherlands', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Belgium', policeNumber: '101', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Luxembourg', policeNumber: '113', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Switzerland', policeNumber: '117', ambulanceNumber: '144', fireBrigadeNumber: '118'),
    EmergencyHelpline(country: 'Austria', policeNumber: '133', ambulanceNumber: '144', fireBrigadeNumber: '122'),
    EmergencyHelpline(country: 'Hungary', policeNumber: '107', ambulanceNumber: '104', fireBrigadeNumber: '105'),
    EmergencyHelpline(country: 'Czech Republic', policeNumber: '158', ambulanceNumber: '155', fireBrigadeNumber: '150'),
    EmergencyHelpline(country: 'Slovakia', policeNumber: '158', ambulanceNumber: '155', fireBrigadeNumber: '150'),
    EmergencyHelpline(country: 'Poland', policeNumber: '112', ambulanceNumber: '999', fireBrigadeNumber: '998'),
    EmergencyHelpline(country: 'Ukraine', policeNumber: '102', ambulanceNumber: '103', fireBrigadeNumber: '101'),
    EmergencyHelpline(country: 'Belarus', policeNumber: '102', ambulanceNumber: '103', fireBrigadeNumber: '101'),
    EmergencyHelpline(country: 'Lithuania', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Latvia', policeNumber: '112', ambulanceNumber: '113', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Estonia', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Finland', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Sweden', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Norway', policeNumber: '112', ambulanceNumber: '113', fireBrigadeNumber: '110'),
    EmergencyHelpline(country: 'Denmark', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Iceland', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Ireland', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Scotland', policeNumber: '999', ambulanceNumber: '999', fireBrigadeNumber: '999'),
    EmergencyHelpline(country: 'Wales', policeNumber: '999', ambulanceNumber: '999', fireBrigadeNumber: '999'),
    EmergencyHelpline(country: 'Northern Ireland', policeNumber: '999', ambulanceNumber: '999', fireBrigadeNumber: '999'),
    EmergencyHelpline(country: 'Greenland', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Faroe Islands', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Monaco', policeNumber: '17', ambulanceNumber: '18', fireBrigadeNumber: '18'),
    EmergencyHelpline(country: 'San Marino', policeNumber: '112', ambulanceNumber: '118', fireBrigadeNumber: '115'),
    EmergencyHelpline(country: 'Vatican City', policeNumber: '112', ambulanceNumber: '118', fireBrigadeNumber: '115'),
    EmergencyHelpline(country: 'Andorra', policeNumber: '110', ambulanceNumber: '116', fireBrigadeNumber: '118'),
    EmergencyHelpline(country: 'Liechtenstein', policeNumber: '117', ambulanceNumber: '144', fireBrigadeNumber: '118'),
    EmergencyHelpline(country: 'Malta', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Slovenia', policeNumber: '113', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Croatia', policeNumber: '192', ambulanceNumber: '194', fireBrigadeNumber: '193'),
    EmergencyHelpline(country: 'Bosnia and Herzegovina', policeNumber: '122', ambulanceNumber: '124', fireBrigadeNumber: '123'),
    EmergencyHelpline(country: 'Serbia', policeNumber: '192', ambulanceNumber: '194', fireBrigadeNumber: '193'),
    EmergencyHelpline(country: 'Montenegro', policeNumber: '122', ambulanceNumber: '124', fireBrigadeNumber: '123'),
    EmergencyHelpline(country: 'Kosovo', policeNumber: '192', ambulanceNumber: '194', fireBrigadeNumber: '193'),
    EmergencyHelpline(country: 'Albania', policeNumber: '129', ambulanceNumber: '127', fireBrigadeNumber: '128'),
    EmergencyHelpline(country: 'Macedonia', policeNumber: '192', ambulanceNumber: '194', fireBrigadeNumber: '193'),
    EmergencyHelpline(country: 'Bulgaria', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Romania', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Moldova', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Armenia', policeNumber: '102', ambulanceNumber: '103', fireBrigadeNumber: '101'),
    EmergencyHelpline(country: 'Azerbaijan', policeNumber: '102', ambulanceNumber: '103', fireBrigadeNumber: '101'),
    EmergencyHelpline(country: 'Georgia', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Kazakhstan', policeNumber: '102', ambulanceNumber: '103', fireBrigadeNumber: '101'),
    EmergencyHelpline(country: 'Uzbekistan', policeNumber: '102', ambulanceNumber: '103', fireBrigadeNumber: '101'),
    EmergencyHelpline(country: 'Turkmenistan', policeNumber: '102', ambulanceNumber: '103', fireBrigadeNumber: '101'),
    EmergencyHelpline(country: 'Kyrgyzstan', policeNumber: '102', ambulanceNumber: '103', fireBrigadeNumber: '101'),
    EmergencyHelpline(country: 'Tajikistan', policeNumber: '102', ambulanceNumber: '103', fireBrigadeNumber: '101'),
    EmergencyHelpline(country: 'Mongolia', policeNumber: '102', ambulanceNumber: '103', fireBrigadeNumber: '101'),
    EmergencyHelpline(country: 'Nepal', policeNumber: '100', ambulanceNumber: '102', fireBrigadeNumber: '101'),
    EmergencyHelpline(country: 'Bhutan', policeNumber: '113', ambulanceNumber: '112', fireBrigadeNumber: '110'),
    EmergencyHelpline(country: 'Maldives', policeNumber: '119', ambulanceNumber: '102', fireBrigadeNumber: '118'),
    EmergencyHelpline(country: 'Sri Lanka', policeNumber: '119', ambulanceNumber: '110', fireBrigadeNumber: '110'),
    EmergencyHelpline(country: 'Bangladesh', policeNumber: '999', ambulanceNumber: '199', fireBrigadeNumber: '199'),
    EmergencyHelpline(country: 'Myanmar', policeNumber: '199', ambulanceNumber: '192', fireBrigadeNumber: '191'),
    EmergencyHelpline(country: 'Thailand', policeNumber: '191', ambulanceNumber: '1669', fireBrigadeNumber: '199'),
    EmergencyHelpline(country: 'Laos', policeNumber: '191', ambulanceNumber: '195', fireBrigadeNumber: '190'),
    EmergencyHelpline(country: 'Cambodia', policeNumber: '117', ambulanceNumber: '119', fireBrigadeNumber: '118'),
    EmergencyHelpline(country: 'Vietnam', policeNumber: '113', ambulanceNumber: '115', fireBrigadeNumber: '114'),
    EmergencyHelpline(country: 'Malaysia', policeNumber: '999', ambulanceNumber: '999', fireBrigadeNumber: '994'),
    EmergencyHelpline(country: 'Singapore', policeNumber: '999', ambulanceNumber: '995', fireBrigadeNumber: '995'),
    EmergencyHelpline(country: 'Indonesia', policeNumber: '110', ambulanceNumber: '118', fireBrigadeNumber: '113'),
    EmergencyHelpline(country: 'Philippines', policeNumber: '117', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Brunei', policeNumber: '993', ambulanceNumber: '991', fireBrigadeNumber: '995'),
    EmergencyHelpline(country: 'East Timor', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Papua New Guinea', policeNumber: '112', ambulanceNumber: '111', fireBrigadeNumber: '110'),
    EmergencyHelpline(country: 'Solomon Islands', policeNumber: '999', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Vanuatu', policeNumber: '112', ambulanceNumber: '112', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Fiji', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Tonga', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Samoa', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Kiribati', policeNumber: '999', ambulanceNumber: '999', fireBrigadeNumber: '999'),
    EmergencyHelpline(country: 'Tuvalu', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Nauru', policeNumber: '110', ambulanceNumber: '111', fireBrigadeNumber: '112'),
    EmergencyHelpline(country: 'Palau', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Marshall Islands', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Micronesia', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Cook Islands', policeNumber: '999', ambulanceNumber: '998', fireBrigadeNumber: '997'),
    EmergencyHelpline(country: 'Niue', policeNumber: '999', ambulanceNumber: '999', fireBrigadeNumber: '999'),
    EmergencyHelpline(country: 'Tokelau', policeNumber: '999', ambulanceNumber: '999', fireBrigadeNumber: '999'),
    EmergencyHelpline(country: 'French Polynesia', policeNumber: '17', ambulanceNumber: '15', fireBrigadeNumber: '18'),
    EmergencyHelpline(country: 'New Caledonia', policeNumber: '17', ambulanceNumber: '15', fireBrigadeNumber: '18'),
    EmergencyHelpline(country: 'Wallis and Futuna', policeNumber: '17', ambulanceNumber: '15', fireBrigadeNumber: '18'),
    EmergencyHelpline(country: 'American Samoa', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Guam', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Northern Mariana Islands', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Puerto Rico', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'U.S. Virgin Islands', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'British Virgin Islands', policeNumber: '999', ambulanceNumber: '999', fireBrigadeNumber: '999'),
    EmergencyHelpline(country: 'Anguilla', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Bermuda', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Cayman Islands', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Montserrat', policeNumber: '999', ambulanceNumber: '999', fireBrigadeNumber: '999'),
    EmergencyHelpline(country: 'Turks and Caicos Islands', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Aruba', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Curacao', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Sint Maarten', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Bonaire', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Saba', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
    EmergencyHelpline(country: 'Sint Eustatius', policeNumber: '911', ambulanceNumber: '911', fireBrigadeNumber: '911'),
  ];
}